version: '3.4'

services:
  traefik:
    image: traefik:v2.2
    ports:
     - 80:80
     - 443:443
    volumes:
     - letsencrypt:/letsencrypt
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    command:
     - --api.insecure=true
     - --api.dashboard=true
     - --providers.docker=true
     - --providers.docker.swarmMode=true
     - --providers.docker.exposedbydefault=false
     - --providers.docker.network=proxy
     - --providers.docker.watch=true
     - --entrypoints.http.address=:80
     - --entrypoints.https.address=:443
     - --certificatesresolvers.letsencrypt.acme.httpChallenge.entrypoint=http
     - --certificatesresolvers.letsencrypt.acme.email=keszi000@gmail.com
     - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.services.traefik.loadbalancer.server.port: '8080'
        traefik.http.routers.traefik-http.entrypoints: http
        traefik.http.routers.traefik-http.rule: Host(`traefik.smartdev.cloud`)
networks:
  proxy:
    external: true
volumes:
  letsencrypt:
    driver: local
